package CORBA;

/**
* org/omg/CORBA/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, August 7, 2016 4:18:53 PM PDT
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (CORBA.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA.FrontEndHelper.type ();
  }

}
