package CORBA;


/**
* org/omg/CORBA/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, August 7, 2016 4:18:53 PM PDT
*/

public interface FrontEndOperations 
{
  String execute (String a);
} // interface FrontEndOperations
